# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazymark" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "84ff15dd88b2e51002b3f78a415764344289e90a4edb2d281234d13e2f54e8b4"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "496fc03647db0c122d4ee14c4d4a6aeaa9404b7ef1775fcc2492bc723de61b7f"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3ba73088b22a48d940d9150c4462ec0d2379cd25802bed23efce7b3fda213ff"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a28dcafd6cba415e161b00ad11661cbc0a0c17db57c63026a87d8259892f64c5"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazymark"
  desc "Terminal Markdown notes and task manager"
  homepage "https://github.com/MathiasDrizzy/lazymark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazymark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazymark"]
    end
  end

  # No zap stanza required
end
