# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazymark" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "8551d33fad940e3569226c85d0426d329ff2873f6f8dc85fa288f2bf1a667677"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62099bef31ca40a28f9dbafb282f0f174d08e65a369e788760c37383418157ec"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b931b672744612e17429cf00b02d3855c8b227d61ec333158e77ec7322ef7d0"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2175d7e9f7ffcf0bd4b1f38d76c3ab8eee7b26a832b3e4a2e16c5ec1382e2dae"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazymark"
  desc "Terminal Markdown notes and task manager"
  homepage "https://github.com/MathiasDrizzy/lazymark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazymark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazymark"]
    end
  end

  # No zap stanza required
end
