# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazymark" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "601ba59cf36b49d346d5209b85db2cabecbae027321afd56e4662f049721c379"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38de32370ec881f75d58439adfcaadbd4e4ed539e8eaee58005fc0644e316c01"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0695c21a7d4b974c7519d8ce03ed5b49feea8a864178fb33eafe3cf2947e7af0"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d862ef72ec86c196201f77ab3b350670e63e385477a47143ab1b60ee77f46bf"
      url "https://github.com/MathiasDrizzy/lazymark/releases/download/v#{version}/lazymark_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazymark"
  desc "Terminal Markdown notes and task manager"
  homepage "https://github.com/MathiasDrizzy/lazymark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazymark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazymark"]
    end
  end

  # No zap stanza required
end
